### ISSUE TITLE
Jellyfin Catalog Version Update

### ISSUE THREAD

**Issue by mcrowson** [jellyfin/jellyfin-plugin-emailnotifications#16]
It looks like the version from the official catalog is 4.0 but I'm seeing 7.0 in the buildspec here. Any plans on updating the plugin in the official version or should I install this manually? If so, are there instructions for building these within the official docker container?

**Comment by crobibero** [comment]
There will be a new release accompanying the release of 10.6

**Comment by mcrowson** [comment]
I also realized I was on a year old version of Jellyfin. Updating that gave me access to some of the updated plugins.
