### ISSUE TITLE
GUID should contain 32 digits.... "There was an error sending the test email. Please check your email settings and try again."

### ISSUE THREAD

**Issue by SCRAFII** [jellyfin/jellyfin-plugin-emailnotifications#9]
Setup: Running on RPi4 behind an traefik reverse proxy with my own domain name.

I tested my SMTP Authentification credentials they are right.

Can't setup E-Mail Notifications, when I try I get the following message:

**"There was an error sending the test email. Please check your email settings and try again."**

My Log:

> [2020-02-08 16:52:04.477 +01:00] [INF] Sending email "test@test.net" with subject "Emby: Jellyfin: Test Notification"
> [2020-02-08 16:52:04.479 +01:00] [INF] Sending email "test@test.net" with subject "Emby: Jellyfin: Test Notification"
> [2020-02-08 16:52:04.485 +01:00] [ERR] Error processing request
> System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
>    at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
>    at System.Guid.TryParseGuidWithNoStyle(ReadOnlySpan`1 guidString, GuidResult& result)
>    at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidStyles flags, GuidResult& result)
>    at System.Guid..ctor(String g)
>    at Emby.Server.Implementations.Library.UserManager.GetUserById(String id)
>    at MediaBrowser.Plugins.SmtpNotifications.Api.ServerApiEndpoints.Post(TestNotification request)
>    at lambda_method(Closure , Object , Object )
>    at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
>    at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
>    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
>    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

Thanks for the Help!

**Comment by helloxz** [comment]
This plug-in doesn't work at all.

**Comment by HanFox** [comment]
I made a PR that should fix this: https://github.com/jellyfin/jellyfin-plugin-emailnotifications/pull/10
